qdrant_grpc_url = "grpc://ef928f5f-6fe3-4d8c-b99d-9d4698ab8349.us-east-1-0.aws.cloud.qdrant.io:6334"
qdrant_db_url= "https://ef928f5f-6fe3-4d8c-b99d-9d4698ab8349.us-east-1-0.aws.cloud.qdrant.io"
qdrant_api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.WhoSsSVxBBc8d8hxRwmQKPfwwZ6qMGAmYsfK3elLx4I"